### ISSUE TITLE
Add git/commit-email-privacy

### ISSUE THREAD

**Issue by pmvald** [pinglue/dev-guides#1]
Add a new mdx file `git/commit-email-privacy` explaining `git log` and how it exposes your emails in the commit - then explain the solution (Github menu for web-based use and `git config` for cli) - ask devs to set thei hashed email for commits - changing commits later is a hard task as I did before!

**Comment by aminsaedi** [comment]
the file should be in `.mdx` format or `.md`? just asking because there is file in `/git` folder with `.md` extension

**Comment by pmvald** [comment]
Lets do it with mdx, in case that in the future we want to add some components to them, hope github page recognize mdx ...
